### ISSUE TITLE
Vagrant support?

### ISSUE THREAD

**Issue by jperry** [fnichol/knife-server#1]
Hi,

Any plans to add vagrant support this way you can do everything offline?  Just wanted to see if anything was in the works before I fork it and try to implement something.

Thanks,
Jay

**Comment by fnichol** [comment]
Yes, as a minimum I'd like to support for "standalone systems" which could be a vagrant instance running with a networked IP address. The `knife server bootstrap standalone` (or something like that) would need a DNS name/IP address as a target (much like `knife bootstrap`) and would run as expected. Do you think this approach would cover off Vagrant or something a little more tailored?

**Comment by jperry** [comment]
yeah I think that should work fine.  Vagrant uses a different port for ssh which I think this plugin supports to set that.  What would be your ETA for this functionality?

**Comment by jperry** [comment]
Hey Fletcher,

I have been making changes on my fork trying to get it to work with vagrant and I'm having troubling identifying where all the chef server stuff is being installed?  Is this missing?  Can you give me a pointer to where all the stuff gets installed?

**Comment by fnichol** [comment]
Hey @jperry,

I just released v0.2.2 of the gem which adds `knife server bootstrap standalone` and a quick example in the README. That example uses host-only networking which other Vagrant instances can talk to (but you could also try bridged networking).

The workhorse that's installing the packages and configuration for a Chef Server is the [Chef::Knife::Bootstrap](https://github.com/opscode/chef/blob/master/chef/lib/chef/knife/bootstrap.rb) knife plugin which is used directly by `Chef::Knife::ServerBootstrapStandalone` and indirectly by `Chef::Knife::ServerBootstrapEc2`. The Bootstrap plugin's job is to run a template (a bash shell script) via SSH on the remote server. The default bootstrap template in this gem is [chef-server-debian.erb](https://github.com/fnichol/knife-server/blob/master/lib/chef/knife/bootstrap/chef-server-debian.erb) which works on Debian and Ubuntu systems (so far).

Give it a shot and if you're running into issues or documentation tweaks, just add a new issue. Thank you for your feedback!

**Comment by jperry** [comment]
Thanks Fletcher I'll try it out and let you know how well it goes.

**Comment by jperry** [comment]
Fletcher, the new standalone option works great.  It would be cool if there was an option to push all the repo stuff to it after it is up and running.

**Comment by fnichol** [comment]
Good to hear! Heh, you're reading my mind me thinks. I've been thinking about how to incorporate something like Spiceweasel's [--extractlocal flag](https://github.com/mattray/spiceweasel#--extractlocal) into another subcommand. In the meantime, this is what I've been using with very enjoyable results. Hoping to get this whole process down to 2 or three knife commands which would kick butt :)

**Comment by jperry** [comment]
Thanks Fletcher for the tip.  I'll check out Spiceweasel.
