### ISSUE TITLE
Instructions for "knife.rb Setup"

### ISSUE THREAD

**Issue by bluemont** [fnichol/knife-server#10]
I'm not sure exactly what to do for the "knife.rb Setup" portion of the installation instructions: "When creating a Chef Server the validation key and admin client key will be installed on your workstation. Therefore, several knife configuration options are required..."

What specific steps should I follow? I've read the Chef pages but I'm not sure what to do first.... setup my workstation? Many of those instructions assume I already have a server ready, which isn't the case; I'm starting from scratch.

**Comment by bluemont** [comment]
After running `knife server bootstrap standalone ...` the first error message I see is:

<pre>
ERROR: Errno::ENOENT: No such file or directory - /etc/chef/validation.pem
</pre>

(Note that this is the last line from the output, even though I think the error is generated somewhere in the middle of the run. That's strange.)

**Comment by bluemont** [comment]
I think I'm getting closer. Here is what I've tried so far -- out of trial and error, picking parts that seemed to make sense from the Chef docs.

A. Edit `/etc/hosts` and add:

<pre>
xxx.xxx.xxx.xxx lixxx-xxx.members.linode.com chef
</pre>

B. Run `knife configure` or edit `~/.chef/knife.rb` so it looks like:

<pre>
log_level :info
log_location STDOUT
node_name 'blue'
client_key '/Users/david/.chef/blue.pem'
validation_client_name 'chef-validator'
validation_key '/etc/chef/validation.pem'
chef_server_url 'http://chef:4000'
cache_type 'BasicFile'
cache_options(path: '/Users/david/.chef/checksums')
</pre>

Notes:
- I'm not sure why I want to specify the `chef_server_url` at this point, since it does not exist.

C. Run `sudo knife configure client /etc/chef` to generate `client.rb` and `validation.pem`.

Now, I get this error:

<pre>
ERROR: Errno::EACCES: Permission denied - /etc/chef/validation.1355081188.pem
</pre>

**Comment by bluemont** [comment]
After thinking about it, running `sudo knife configure client ...` as I show above didn't seem to make sense. So I deleted `/etc/chef` from my local machine. Then I did the following. Things appear to be working now.

A. Run `knife configure` or edit `~/.chef/knife.rb` to contain:

<pre>
log_level :info
log_location STDOUT
node_name 'blue'
client_key '/Users/david/.chef/blue.pem'
validation_client_name 'chef-validator'
validation_key '/Users/david/.chef/validation.pem'
chef_server_url 'http://chef:4000'
cache_type 'BasicFile'
cache_options(path: '/Users/david/.chef/checksums')
</pre>

(Note: the only change was to the validation_key line. This means that I don't need sudo to copy the key to the proper location.)

B. Do not run `knife configure client ...`.

C. Run `knife server bootstrap standalone ...`.

The output is:

<pre>
...
-----> Bootstraping Chef Server on chef is complete.
WARNING: No knife configuration file found
Creating initial API user...
Created client[root]
Configuration file written to /root/.chef/knife.rb
</pre>

For those that have done this before, does this seem correct? I don't like that I'm running the server bootstrap as root.

**Comment by fnichol** [comment]
Sorry for your pain here :(

Do you think the commit to the README above will help future users of the gem? If not, I'm very open to help in this section especially.

Are you still having issues getting this running? I agree, you shouldn't have to run the `knife server bootstrap` subcommands as root.

Thanks @bluemont!

**Comment by ghost** [comment]
Your new documentation uses both ~/.chef/ and ~/.chef.d/ which I found confusing.  Can you switch to using one of the two only?  Thanks.

**Comment by ghost** [comment]
Oh, you must have ~/.chef/ since knife insists.  You might also need ~/.chef.d/ if the knife.rb says too.  Still that's confusing.  Wouldn't be simpler to use a name that doesn't resemble .chef such as .knife-server.d ?

**Comment by fnichol** [comment]
If we can get a basic knife.rb setup if one does not exist (#25 #9), this should simplify the process and docs. In this case I'll nix any mention of `~/.chef.d/` since it wouldn't be required. I use this myself, but the tool shouldn't have to bend to my preferences, especially if they aren't a default preference :smile:.

I'm tracking this for a 1.1.0 release.
