### ISSUE TITLE
use of set -e in bootstrap scripts

### ISSUE THREAD

**Issue by erikh** [fnichol/knife-server#12]
Wondering if you'd consider patches that added `set -e` to the bootstrap scripts (and dealt with the consequences). Run into a few server creations where, for whatever reason, dpkg flips out, or chef doesn't converge properly, and the pems just have output from cat (can't find file blabla) in them, which obviously gives knife hives.

It could also be used to check the result of the server creation itself -- I'm automating the use of this tool, so knowing when it succeeds or fails is very handy.

It's obviously a lot more work to maintain though, which is why I'm asking beforehand.

**Comment by fnichol** [comment]
I like this idea, I'd rather fail fast anyway. And you're right, this should help in more automated workflows. Please proceed!

**Comment by erikh** [comment]
probably in a few weeks here. thanks!

**Comment by fnichol** [comment]
Looks like we have `set -e` set in all templates so far which I agree is the desired behavior (fail fast). Yeah!
