### ISSUE TITLE
Standalone bootstrap requires any arbitrary identity file

### ISSUE THREAD

**Issue by bendemaree** [fnichol/knife-server#14]
Hello...wonderful library, thanks for all of your work!

Just wanted to let you know of a potential bug.  When using `knife server bootstrap standalone` (in this case against a vagrant-provisioned box), the `--identity-file` option is in fact required.  If it is not passed with some key, the `net-ssh` command is called with an empty keys argument, which it tries to use.  The error given without it is

`/Library/Ruby/Gems/1.8/gems/net-ssh-2.2.2/lib/net/ssh/authentication/key_manager.rb:64:in `expand_path': can't convert nil into String (TypeError)`

Just to clarify, an associated key is not required, just any key.

The full command I am executing is

`knife server bootstrap standalone --node-name master --host master --identity-file ~/mykey.pem --ssh-user vagrant --ssh-password vagrant`

Thanks; if I knew more Ruby I'd fix 'er up myself.  Alas...

**Comment by fnichol** [comment]
Thanks @bendemaree for reporting, and you are right on here. I just pulled in @erikh's #15 and cutting v0.3.3 now. If we didn't beat this one down, please reopen. Thank you!

**Comment by bendemaree** [comment]
Great @fnichol and @erikh!  Prompt fix!  I'll be able to pull it down soon and test.

Happy holidays!
