### ISSUE TITLE
Why Forbidden for all those apt packages?

### ISSUE THREAD

**Issue by millisami** [fnichol/knife-server#16]
I setup the local VM. and started to create a chef-server standalone, but all thoses packages list gets 403 Forbidden requests therefore couldn't install anything.

The gist log is here https://gist.github.com/4563576

**Comment by ghost** [comment]
Are you able to fetch the packages using other software like wget or curl or firefox?
Can you try:
    wget http://np.archive.ubuntu.com/ubuntu/pool/main/n/ncurses/ncurses-bin_5.9-1ubuntu5_i386.deb

**Comment by millisami** [comment]
@nutznboltz I didn't bother much and changed all the occurances of `np` in the `/etc/apt/sources.list` to `us` and all started working.
