### ISSUE TITLE
How to reset/recove the admin password?

### ISSUE THREAD

**Issue by millisami** [fnichol/knife-server#18]
I've installed the chef-server and when I go to log-in and use the default password, I cannot login. 

How can I reset the password of the admin user?

![Chef Server](https://f.cloud.github.com/assets/47914/81583/a18e2a0e-6341-11e2-90b4-d6f9f3365cee.jpg)

**Comment by erikh** [comment]
The default password is 'chefchef'. It's in the README: https://github.com/fnichol/knife-server/blob/master/README.md

**Comment by millisami** [comment]
Thanks.
