### ISSUE TITLE
knife server bootstrap sub-command not supported

### ISSUE THREAD

**Issue by jperry** [fnichol/knife-server#2]
The readme documentation talkes about a sub command "knife server bootstrap" but that doesn't exist.  Only "knife server bootstrap ec2" exists.

**Comment by fnichol** [comment]
Good point; I meant that section to be for common "bootstrap *" subcommands rather than an actual invokable subcommand. Would a heading rename help clear that up?

**Comment by jperry** [comment]
I think so, as when I first read that I almost thought I could use that against a vagrant box to install a chef server on it.
