### ISSUE TITLE
Option for specifying the chef-server version?

### ISSUE THREAD

**Issue by millisami** [fnichol/knife-server#26]
Hi,
I was trying to find the option to specify which chef-server version to bootstrap since the release of the chef 11.

I found this pull req https://github.com/fnichol/knife-server/pull/22 that might support this but not sure enough.

Or is there any other option?

**Comment by fnichol** [comment]
Ok, this should be resolved with the 1.0.0 release (just out the door). This is the first release to support installing Chef 11 servers (which is also now the default). You can use the `--bootstrap-version` flag to set a specific omnibus package version, or set the value to `"10"` to install a Chef 10 server. The default (unset) value will install the latest stable release from http://www.opscode.com/chef/install/.

Take a quick skim of the [CHANGELONG](https://github.com/fnichol/knife-server/blob/master/CHANGELOG.md), and give it a shot without the flag if you're looking for a Chef 11 server.

Thanks!
