### ISSUE TITLE
Please enter a password for the new user: stty: standard input: Invalid argument

### ISSUE THREAD

**Issue by millisami** [fnichol/knife-server#28]
@fnichol , I tried with the latest release of knife-server and its works.
But at the end, it complains about the `WARNING: No knife configuration file found`
I tried it twice:
1. adding `knife.rb` in `./.chef` directory
2. adding `knife.rb` file in the local dir itself
Both didn't work.
I followed it on the README as well, but where should I put the `knife.rb` file.
One may be in the `~/.chef/knife.rb`, this file is also there.
But I want it to be in the project local directory.

```
192.168.33.10 Deleting user knifey ...
192.168.33.10 
192.168.33.10 
192.168.33.10 Finished in 49.75 seconds
192.168.33.10 
192.168.33.10 70 examples, 0 failures
192.168.33.10 
192.168.33.10        Pedant suite finished
192.168.33.10 
192.168.33.10 -----> Bootstraping Chef Server on chef11.server.com is complete.
192.168.33.10 
WARNING: No knife configuration file found
Creating initial API user...
Please enter a password for the new user: stty: standard input: Invalid argument
stty: standard input: Invalid argument
stty: standard input: Invalid argument

Created user[root]
Configuration file written to /root/.chef/knife.rb
```

Where to put it?

**Comment by fnichol** [comment]
Did you get a fully working Chef Server at the end?

Most of the output post `"-----> Bootstraping…"` is STDOUT from the Chef server. Under the covers a `knife configure --initial` is performed for the root user which sets up a knife.rb and root Chef user. The best I could do was to [pipe a password](https://github.com/fnichol/knife-server/blob/master/lib/knife/server/credentials.rb#L55-L56) into the `knife configure` command.

Maybe there is a way to silence these errors as they are standard operation procedure

**Comment by erikh** [comment]
my guess is `knife configure -i` is running `stty noecho` or similar. `stty sane` might fix it, or ensuring pty allocation is done with ssh (`-t` argument to cli tool, not sure with net-ssh) might also.

if the latter is the case, this might fix the sudo issues as well.

**Comment by millisami** [comment]
Though the server gets installed and works.
@erikh 's suggestion might work, but I don't have any much knowledge about that `stty noecho` or `stty name` 

The following is the structure:

```
root@chef11-on-vagrant:/etc/chef-server# tree
.
├── admin.pem
├── chef-server.rb
├── chef-server-running.json
├── chef-server-secrets.json
├── chef-validator.pem
└── chef-webui.pem

0 directories, 6 files
root@chef11-on-vagrant:/etc/chef-server# cd /root/.chef/
root@chef11-on-vagrant:~/.chef# tree
.
├── knife.rb
└── root.pem

0 directories, 2 files
root@chef11-on-vagrant:~/.chef#
```

**Comment by erikh** [comment]
It probably doesn't "really" matter, but it's a UI wart I suppose.

millisami notifications@github.com wrote:

> Though the server gets installed and works.
> @erikh 's suggestion might work, but I don't have any much knowledge
> about that `stty noecho` or `stty name` 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fnichol/knife-server/issues/28#issuecomment-14344361

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by erikh** [comment]
So, I'm pretty sure I solved this dealing with a separate issue in chef-workflow -- you can tell Net::SSH to request a pty, which I had to do for sudo in certain cases.

Here's the relevant code, working great for my needs over there: https://github.com/chef-workflow/chef-workflow/blob/master/lib/chef-workflow/support/ssh.rb#L47-L51

Worth a shot at least.

**Comment by fnichol** [comment]
I had another look at this issue and while requesting a pty does help resolve these kinds of issues, it looks our particular error happens at least one further fork-and-exec down (by way of net-ssh running a knife command which is then using sudo).

As a less than ideal resolution, I have redirected this warning (on stderr) to a temporary logfile in f6145bf8bc1befc0066d24669c1395a38e9bcb8d and made the plugins die whenever a non-zero exit code is thrown from _any_ remote SSH command by default in 2123b64c8b8345723fe17988b7ed2ed9f59b4150.

It is my hope that by removing the innocuous warning, keeping track of it (just in case) and dying at the first sign of trouble will keep us honest enough here.

Thank you all!
