### ISSUE TITLE
backup clients

### ISSUE THREAD

**Issue by josephholsten** [fnichol/knife-server#31]
possibly by leaving backup to https://github.com/mdxp/knife-backup

**Comment by josephholsten** [comment]
the meat of that implementation is at https://github.com/mdxp/knife-backup/blob/master/lib/chef/knife/backup_export.rb#L88

**Comment by fnichol** [comment]
Looking back at the backup/restore code, I'm fairly certain that Chef's `knife download /` and `knife upload /` may be better replacements that are supported out of the box. I'll make at least one more release with the backup/restore plugins intact, then may drop them in a major version bump. Sound reasonable?

**Comment by ranjib** [comment]
:+1:
