### ISSUE TITLE
knife server bootstrap ec2 fails with "Job failed to start"

### ISSUE THREAD

**Issue by trtg** [fnichol/knife-server#32]
This gem seems like it would be great for my needs, but bootstrapping is not working as you can see below. Any idea how to debug this? I noticed that you've made the node-name parameter mandatory- are there any requirements on the structure of this value? Your docs seem to imply it should be an FQDN- but how would that work if you don't even know the public IP of the instance until it comes up?

knife server bootstrap ec2 -I $AMI_ID -k $KEY_NAME --ssh-key $KEY_FILE --ssh-user ubuntu -f $INSTANCE_TYPE --node-name $NODE_NAME

EC2 security group 'infrastructure' exists
Inbound security group rule icmp(-1 -> -1) exists
Inbound security group rule tcp(0 -> 65535) exists
Inbound security group rule udp(0 -> 65535) exists
Inbound security group rule tcp(22 -> 22) exists
Inbound security group rule tcp(443 -> 443) exists
Inbound security group rule tcp(444 -> 444) exists
Instance ID: i-19303e7b
Flavor: m1.small
Image: ami-137bcf7a
Region: us-east-1
Availability Zone: us-east-1c
Security Groups: infrastructure
Tags: {"Role"=>"chef_server", "Name"=>"the_chef_server"}
SSH Key: mykey

Waiting for server...............
Public DNS Name: ec2-23-22-225-42.compute-1.amazonaws.com
Public IP Address: 23.22.225.42
Private DNS Name: domU-12-31-39-09-9C-B8.compute-1.internal
Private IP Address: 10.210.163.70

Waiting for sshd......done
Bootstrapping Chef on ec2-23-22-225-42.compute-1.amazonaws.com
ec2-23-22-225-42.compute-1.amazonaws.com start: Job failed to start

**Comment by fnichol** [comment]
@trtg While I realize that a long period of time has elapsed, would this still be an issue for you? If it's still relevant and present in the latest stable gem release, then please reopen. In the interest of a little garden tending, I'll close this out in the meantime. Thank you!
