### ISSUE TITLE
Package for chef server 11 not available

### ISSUE THREAD

**Issue by dagi3d** [fnichol/knife-server#36]
If I try to bootstrap my local machine with the following command
    knife server bootstrap standalone --node-name chef.traity.dev --host 192.168.33.11 --ssh-user vagrant --ssh-password vagrant
I get the following output:

```
Bootstrapping Chef on 192.168.33.11
192.168.33.11 hostname stop/waiting
192.168.33.11
192.168.33.11 -----> Downloading Chef Server package from http://www.opscode.com/chef/download-server?p=ubuntu&pv=12.04&m=i686&prerelease=false to /tmp/tmp.7VpIovrT/chef__amd64.deb
192.168.33.11
```

and that's it. The procedure just stops there
It seems that the url  http://www.opscode.com/chef/download-server?p=ubuntu&pv=12.04&m=i686&prerelease=false is broken

In my case the package for the 11 version according to the opscode download page, would be at https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.0.6-1.ubuntu.12.04_amd64.deb

**Comment by erikh** [comment]
Opscode provides no 32-bit omnibus packages for chef 11.

For what it's worth, actually telling you it didn't work is either already
merged, or in an outstanding pull request I filed from two weeks ago or so
(and is expected to be merged), can't remember now.

**Comment by erikh** [comment]
Also, just to be really clear, the link you provide is to a 64-bit package,
and the link being fetched by knife-server is requesting a 32-bit one --
likely because your VM is 32-bit. If it's a 64-bit VM, that's a bug.

**Comment by dagi3d** [comment]
It was a ubuntu64 vagrant box, but it seems it detected the i686 cpu. just used another box with amd64 and the package was downloaded correctly
