### ISSUE TITLE
encounter error on downloading the package. 

### ISSUE THREAD

**Issue by sstrato** [fnichol/knife-server#38]
## i tried this command

 knife server bootstrap standalone  --node-name 172.30.10.10 --ssh-user vagrant  --ssh-password vagrant --host 172.30.10.10 --prerelease --sudo 
## and the output is like below

Bootstrapping Chef on 172.30.10.10
172.30.10.10        Hostname is correct, so skipping...
172.30.10.10 
172.30.10.10 -----> Downloading Chef Server package from http://www.opscode.com/chef/download-server?p=ubuntu&pv=12.04&m=x86_64&prerelease=true to /tmp/tmp.yTzWO12T/chef__amd64.deb
172.30.10.10 
172.30.10.10 >>>>>> We encountered an error downloading the package.
## i tested access that url through wget and i got this

for i in `seq 1 10`; do curl -s -w "%(http_code)\n" "http://www.opscode.com/chef/download-server?p=ubuntu&pv=11.04&m=x86_64&prerelease=true"; done;
Internal Server Error</h1>%(http_code)
Internal Server Error</h1>%(http_code)
Internal Server Error</h1>%(http_code
Internal Server Error</h1>%(http_code)
Internal Server Error</h1>%(http_code)
Internal Server Error</h1>%(http_code)
Internal Server Error</h1>%(http_code)
Internal Server Error</h1>%(http_code)
Internal Server Error</h1>%(http_code)
Internal Server Error</h1>%(http_code)

**Comment by fnichol** [comment]
I believe there was a problem concerning the Omnitruck API endpoint but that should be resolved now. If this isn't the case, let's reopen and make sure the issue is good and dead. Thanks!
