### ISSUE TITLE
I am trying to set this up on EC2 knife-server keeps asking me for root password

### ISSUE THREAD

**Issue by zacksiri** [fnichol/knife-server#4]
So what do i put for the root password? 

I can't seem to get it to work.

**Comment by zacksiri** [comment]
OK i managed to figure this out i had to add an -i option and specify the path to the identity file this should be in the documentation as well

i tried setting knife[:identity_file] and that didn't work

**Comment by fnichol** [comment]
Sorry about the confusion, this hadn't come up for me before. I had always loaded my EC2 SSH key into my key agent before provisioning instances or logging in (with `ssh-add ~/.ssh/mykey`). As a result I hadn't used the `---identity-file` option directly before (hence this inconsistency).

The two pull requests #7 #11 should address this issue and allow you to use the option off the CLI or set in `knife.rb`. If I'm mistaken, please reopen. Thank you!
