### ISSUE TITLE
Cookbooks?

### ISSUE THREAD

**Issue by jblaine** [fnichol/knife-server#44]
Fletcher, any chance this will ever backup cookbooks (all versions) from the server? Sure, they're in SCM, but nobody wants to track down version 0.4.9 (in git) for the production environment and upload it to the server, etc. Especially in a bad situation where the Chef server is needing to be restored.

**Comment by dmorrison** [comment]
You can download all cookbook versions using `knife download` with `versioned_cookbooks true` set in knife.rb. Would this work for you?

See the description of `versioned_cookbooks` [here](http://docs.opscode.com/config_rb_knife.html) for a little more info.

**Comment by jblaine** [comment]
Yup, that'll work.

**Comment by dmorrison** [comment]
Cool. Overall, I'm confused about why the backup and restore commands are needed, and I actually opened issue [#52](https://github.com/fnichol/knife-server/issues/52) to clarify this.
