### ISSUE TITLE
How to use --format?

### ISSUE THREAD

**Issue by xpe** [fnichol/knife-server#46]
Am I doing something wrong by trying this?

``` sh
bundle exec knife linode server list --format summary
```

I've also tried `json`, `text` and others without seeing any difference.

(My goal is to distinguish between public and private IP addresses in the output.)

Should I check with the linode plugin instead?

**Comment by fnichol** [comment]
Hey @xpe!

You're correct that the above logic would be in the opscode/knife-linode project. Sadly though, the `knife linode server list` command output only uses the [table formatting](https://github.com/opscode/knife-linode/blob/master/lib/chef/knife/linode_server_list.rb#L66) and doesn't currently have JSON or text output.

If it's still of interest, this could be a feature request for opscode/knife-linode that they would be willing to entertain. Thanks!
