### ISSUE TITLE
ERROR: Errno::EACCES: Permission denied - /etc/chef/validation.pem

### ISSUE THREAD

**Issue by zacksiri** [fnichol/knife-server#5]
I am getting this error after the boostrap is complete

**Comment by xdissent** [comment]
You need to set your `validation_key` path in `knife.rb`. If you're using chef-bootstrap, setting a `KNIFE_SERVER_NAME` env var is enough to trigger this automatically, placing your validation key in a file named after your user and chef server in `~/.chef.d`. Or you could actually create `/etc/chef` and that would work too.

**Comment by fnichol** [comment]
Does the commit above help clarify the need for user-writable locations for `client_key` and `validation_key`? I'm open to moving things around to help make this easier to follow.

If I've missed the boat here, or you're still having problems, please reopen. Thank you!

**Comment by RakeshMsr** [comment]
simple just add sudo command. like this 

$ sudo chef-client

**Comment by kiranbanda420** [comment]
I do got above error 
Tried $ sudo chef-client
Succeded Thanks@RakeshMsr.
