### ISSUE TITLE
NoMethodError: undefined method `split' for :tags:Symbol

### ISSUE THREAD

**Issue by jparal** [fnichol/knife-server#54]
knife server bootstrap ec2 fail with following error:

``` bash
ERROR: knife encountered an unexpected error
This may be a bug in the 'server bootstrap ec2' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `split' for :tags:Symbol
```

**Comment by jparal** [comment]
I forgot to add version number:
v1.1.0

**Comment by fnichol** [comment]
@jparal I believe I have sorted this issue out but now cannot remember in which commit so that I can link back :cry: 

So, once I cut the next release shorty, if you are still experiencing this issue, could you re-open so we get it smashed for good?

Thanks!
