### ISSUE TITLE
security groups specified with '-G' are not allowed

### ISSUE THREAD

**Issue by joune** [fnichol/knife-server#58]
I'm trying to boostrap a chef server on EC2 with a command like this (some params obfuscated):

> knife server bootstrap ec2 --config knife-ec2.rb --node-name my-chef-server --image ami-b66ed3de --flavor t1.micro --security-group-ids sg-XXXX --subnet subnet-XXXX --region us-east-1 --availability-zone us-east-1a --ssh-user ec2-user --identity-file KeyPair.pem --webui-enable

and I get the following error:
ERROR: You are using a VPC, security groups specified with '-G' are not allowed, specify one or more security group ids with '-g' instead.

I'm specifically using --security-group-ids rather than --security-groups for this reason but I still get the error. 

Am I doing something wrong?
thanks.

**Comment by joune** [comment]
Sorry, seems like it was a dependencies problem on my side. Closing the issue.

**Comment by Azrael808** [comment]
Hey @joune could you clarify what the dependency problems you had were?

I have run into the exact issue you describe above and this is with a fresh install of the `ChefDK` and relevant additional gems (knife-ec2 and knife-server). I've tried to simply specify the subnet-id and have the bootstrap process create the security group for me and I've explicitly mentioned a pre-existing Security Group that I'd created using the `--security-group-ids`, both failed.

Here's the command I'm using:

```
knife server bootstrap ec2 --node-name chef.example.com --webui-enable --distro "chef11/omnibus" --subnet subnet-xxxxxxxx --security-group-ids sg-yyyyyyyy
```
