### ISSUE TITLE
Bootstrap start ok, but then fails with ERROR: Net::SSH::AuthenticationFailed: ubuntu

### ISSUE THREAD

**Issue by TokMedia** [fnichol/knife-server#6]
my command was
knife server bootstrap ec2 -N xxx.xxx.com -i key.pem -S tokey -f t1.micro -I ami-a29943cb --ebs-no-delete-on-term -x ubuntu

It started well, but then
...
ec2-XXXX.compute-1.amazonaws.com -----> Bootstraping Chef Server on chefserver.toksnn.com is complete.

Instance ID: i-32229a48
Flavor: m1.small
Image: ami-a29943cb
Region: us-east-1
Availability Zone: us-east-1b
Security Groups: infrastructure
Security Group Ids: default
Tags: {"Role"=>"chef_server", "Name"=>"xx.xx.com"}
SSH Key: key
Root Device Type: ebs
Root Volume ID: vol-b43b4fcf
Root Device Name: /dev/sda1
Root Device Delete on Terminate: true
Public DNS Name: ec2x.x.compute-1.amazonaws.com
Public IP Address: 
Private DNS Name: 
Private IP Address: 
Environment: _default
ERROR: Net::SSH::AuthenticationFailed: ubuntu

**Comment by xdissent** [comment]
It looks like `Net::SSH.start` isn't getting the `identity_file` option. The same thing happens for standalone. I'm sending a PR in a moment with fixes.

**Comment by xdissent** [comment]
See PR #7

**Comment by fnichol** [comment]
I just merged in @xdissent's work and will cut a release. If we're wrong and this is still an issue, please reopen. Thank you for reporting!
