### ISSUE TITLE
WARNING: No knife configuration file found

### ISSUE THREAD

**Issue by bluemont** [fnichol/knife-server#9]
<pre>
knife server bootstrap standalone \
> --node-name xxxxx.members.linode.com \
> --host xxxxx.members.linode.com \
> --ssh-user root \
> --ssh-password xxxxxxx
WARNING: No knife configuration file found
Bootstrapping Chef on xxxxx.members.linode.com
xxxxx.linode.com + setup
xxxxx.linode.com + apt-get update
...
</pre>

Is there a step before that I'm missing? I'm rusty with my knife.

**Comment by bluemont** [comment]
Should the instructions say to run `knife configure` first?

**Comment by fnichol** [comment]
Would the additional comment in the README have helped? While it's possible to run `knife configure`, I would suggest it may be easier to author this file yourself to give you full control. These days I'm using a [portable knife.rb](https://github.com/fnichol/chef-bootstrap-repo/blob/master/.chef/knife.rb) that gets dropped into a projects root directory under `.chef/knife.rb`. It relies on environment variables to set a few variables, and comes out of [chef-bootstrap-repo](https://github.com/fnichol/chef-bootstrap-repo).

**Comment by erikh** [comment]
@fnichol hmm -- maybe a commandline arg to specify a dir to create and dump the knife.rb and associated creds? Might be nice for those just wanting to do the basics; I do something like this in chef-workflow here: https://github.com/chef-workflow/chef-workflow/blob/master/lib/chef-workflow/support/knife.rb#L31

If you create it for them, assume some "standards" and maybe spit out some basic text telling them where to put stuff, like for cookbooks and roles and so forth.

**Comment by fnichol** [comment]
We should be able to add a very basic knife.rb configuration if it does not currently exist, which is being tracked in #25. I didn't want to further delay a gem release, so I'd like to deal with this in a 1.1.0 release.
